version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/build
   
hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 60
      runas: root

  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 60
      runas: root
      
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 60
      runas: root

  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 60
      runas: root

  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 60
