# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        
    - name: Build with Maven
      run: mvn -B package --file demo/pom.xml
      
    - name: Make Bundle
      run: zip -qq -r ./demo-0.0.1-SNAPSHOT.zip .
      shell: bash

    - name: Upload to AWS S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_S3_UPLOAD_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_UPLOAD_KEY }}
      run: |
        aws s3 cp \
          --region ap-northeast-2 \
          ./demo-0.0.1-SNAPSHOT.zip s3://s3-cicd-test

    - name: AWS Deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_S3_UPLOAD_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_UPLOAD_KEY }}
      run: |
        aws deploy create-deployment \
          --region ap-northeast-2 \
          --application-name code-deploy-test \
          --deployment-config-name CodeDeployDefault.AllAtOnce \
          --deployment-group-name code-deploy-group-test \
          --s3-location bucket=s3-cicd-test,bundleType=zip,key=demo-0.0.1-SNAPSHOT.zip
